import { DOMAINS } from '../questions.js';

export const ACTIVE_INSTRUMENT_VERSION = 'V0.3';
export const LEGACY_INSTRUMENT_VERSION = 'V0.2';

// Setiap baris dikurasi terhadap substansi pertanyaan. Teks sebelum `|` adalah
// judul ringkas; teks setelahnya menjelaskan kondisi nyata yang dipilih responden.
const CURATED = {
  vision_01: ['behavioral_maturity','learner_outcome_direction',['Belum tergambar|Belum ada gambaran bersama tentang santri yang ingin dibentuk.','Masih berupa harapan umum|Gambaran ada dalam ucapan pimpinan, tetapi berbeda-beda ketika dijelaskan.','Gambaran sudah disepakati|Ciri santri yang ingin dibentuk sudah tertulis dan dipahami sebagian besar tim.','Dipakai menilai program|Tim memeriksa kegiatan berdasarkan kontribusinya pada profil santri yang disepakati.','Diperbaiki dari hasil nyata|Profil santri dan program diperbarui berdasarkan hasil perkembangan santri.']],
  vision_02: ['behavioral_maturity','leadership_priority_clarity',['Prioritas belum jelas|Banyak agenda berjalan bersamaan tanpa pilihan utama yang tegas.','Ada fokus sementara|Pimpinan menyebut beberapa fokus, tetapi urutan dan batasnya sering berubah.','Prioritas periode disepakati|Tim mengetahui sasaran utama semester atau tahun ini dan urutannya.','Kemajuan rutin diperiksa|Pimpinan meninjau capaian prioritas dan mengatasi hambatan yang ditemukan.','Prioritas disesuaikan berbasis hasil|Fokus berikutnya ditetapkan dari capaian, perubahan kebutuhan, dan pelajaran pelaksanaan.']],
  vision_03: ['extent','strategic_direction_understanding',['Hanya pimpinan yang tahu|Arah besar pesantren belum dipahami guru, pengasuh, dan staf.','Dipahami beberapa orang|Orang dekat pimpinan memahami arah, tetapi pemahaman belum merata.','Dipahami sebagian besar tim|Guru, pengasuh, dan staf dapat menjelaskan arah yang sama dengan bahasa mereka.','Terlihat dalam keputusan kerja|Pemahaman arah tampak pada pilihan program dan prioritas kerja lintas unit.','Pemahaman terus diselaraskan|Perbedaan pemahaman ditemukan, dibahas, dan diperbaiki secara berkala.']],
  vision_04: ['behavioral_maturity','program_strategy_alignment',['Program mengikuti kebiasaan|Kegiatan diteruskan karena sudah biasa, tanpa memeriksa kaitannya dengan visi.','Kaitan program belum konsisten|Sebagian program dikaitkan dengan visi, sebagian lain berjalan sendiri.','Setiap program punya kaitan jelas|Tujuan program menjelaskan bagian visi yang hendak diwujudkan.','Kesesuaian program ditinjau|Program yang tidak mendukung visi diperbaiki, digabung, atau dihentikan.','Portofolio program dioptimalkan|Sumber daya dialihkan berdasarkan bukti kontribusi program terhadap visi.']],
  vision_05: ['behavioral_maturity','target_measurability',['Target masih berupa niat|Target memakai kata umum sehingga kemajuannya sulit dikenali.','Sebagian target mulai terukur|Ada angka atau tenggat pada beberapa target, tetapi belum konsisten.','Target konkret dan bertenggat|Hasil yang diharapkan, ukuran, penanggung jawab, dan waktu sudah jelas.','Kemajuan target dilacak|Capaian dan penyimpangan target diperiksa dengan data yang disepakati.','Target ditingkatkan berbasis hasil|Ukuran dan ambisi target diperbaiki setelah menilai capaian periode sebelumnya.']],
  vision_06: ['frequency','leadership_progress_review',['Tidak pernah ditinjau|Target dibuat, tetapi pimpinan tidak memeriksa kemajuannya.','Ditinjau saat ada masalah|Pemeriksaan baru dilakukan ketika keterlambatan atau keluhan muncul.','Ditinjau sesuai jadwal|Pimpinan memeriksa kemajuan target pada waktu yang sudah ditetapkan.','Tinjauan menghasilkan tindakan|Setiap penyimpangan memiliki keputusan, penanggung jawab, dan tenggat perbaikan.','Pola tinjauan disempurnakan|Cara dan frekuensi review diperbaiki berdasarkan kualitas tindak lanjutnya.']],
  vision_07: ['behavioral_maturity','evidence_based_decision',['Mengandalkan perkiraan|Keputusan penting terutama dibuat dari kebiasaan atau pendapat terkuat.','Data dicari tidak teratur|Data kadang dipakai, tetapi sumber dan ketepatannya belum pasti.','Data relevan menjadi bahan|Keputusan penting memakai data dan penjelasan kondisi lapangan yang dapat diperiksa.','Asumsi dan hasil diperiksa|Pimpinan membandingkan hasil keputusan dengan data awal dan dampaknya.','Pembelajaran memperbaiki keputusan|Pola keputusan diperbarui dari bukti keberhasilan, kegagalan, dan perubahan konteks.']],
  vision_08: ['extent','policy_change_communication',['Perubahan diketahui mendadak|Pelaksana menerima aturan baru tanpa penjelasan alasan atau tujuan.','Penjelasan hanya ke sebagian pihak|Orang tertentu memahami alasan perubahan, tetapi pesan tidak sampai merata.','Alasan dan tujuan dijelaskan|Pihak terdampak menerima penjelasan yang sama sebelum atau saat perubahan berlaku.','Pemahaman pelaksana diperiksa|Pertanyaan dan salah tafsir dicatat lalu dijelaskan kembali.','Komunikasi perubahan dievaluasi|Cara menyampaikan kebijakan diperbaiki dari umpan balik dan masalah pelaksanaan.']],
  vision_09: ['behavioral_maturity','decision_authority_clarity',['Semua menunggu pimpinan|Keputusan rutin pun sering tertahan sampai pimpinan memberi arahan.','Sebagian boleh diputuskan|Unit mengambil beberapa keputusan, tetapi batasnya belum jelas dan sering berubah.','Batas keputusan dipahami|Keputusan rutin dan yang harus dinaikkan sudah dibedakan serta umumnya dipahami.','Jalur keputusan diperiksa|Keputusan salah jalur dan eskalasi berlebihan ditinjau lalu dikoreksi.','Kewenangan terus disempurnakan|Pembagian keputusan diperbaiki dari pengalaman pelaksanaan dan hasilnya diperiksa.']],
  vision_10: ['behavioral_maturity','leadership_continuity',['Kegiatan mudah berhenti|Banyak pekerjaan dan keputusan menunggu saat pimpinan utama tidak ada.','Ada pengganti informal|Beberapa orang mengambil alih, tetapi mandat dan informasi belum lengkap.','Pengganti dan mandat jelas|Tugas penting, batas keputusan, serta akses informasi sudah disiapkan.','Kesiapan pengganti diuji|Ketiadaan pimpinan pernah dijalani atau disimulasikan dan kendalanya diperbaiki.','Suksesi diperbarui berkala|Kapasitas pengganti dan pembagian mandat ditinjau mengikuti perubahan organisasi.']],

  governance_01: ['behavioral_maturity','organization_structure_fit',['Bagan tidak mencerminkan kerja|Nama jabatan ada, tetapi pekerjaan sehari-hari mengikuti hubungan informal.','Sebagian peran sesuai|Beberapa unit bekerja sesuai struktur, sementara tanggung jawab lain tumpang tindih.','Struktur sesuai proses utama|Unit, jalur koordinasi, dan tanggung jawab mencerminkan pekerjaan yang nyata.','Kesenjangan struktur ditinjau|Beban, tumpang tindih, dan jalur koordinasi diperiksa lalu ditindaklanjuti.','Struktur disesuaikan berkala|Perubahan layanan dan kebutuhan menjadi dasar memperbarui struktur.']],
  governance_02: ['extent','role_clarity',['Tugas utama belum jelas|Orang menerima pekerjaan dari banyak arah tanpa batas tanggung jawab yang pasti.','Jelas bagi beberapa jabatan|Sebagian orang punya uraian tugas, tetapi penerapannya berbeda antarunit.','Tugas utama dipahami|Setiap orang dapat menjelaskan hasil utama dan tanggung jawab perannya.','Kejelasan tugas diperiksa|Tumpang tindih, pekerjaan kosong, dan kebingungan peran ditinjau serta diperbaiki.','Peran berkembang terarah|Uraian tugas diperbarui mengikuti perubahan proses, beban, dan kompetensi.']],
  governance_03: ['behavioral_maturity','decision_authority_clarity',['Wewenang bergantung orang|Batas keputusan berubah mengikuti siapa yang sedang bertugas atau paling senior.','Ada kebiasaan tidak tertulis|Sebagian batas dipahami, tetapi kasus penting masih sering diperdebatkan.','Batas wewenang ditetapkan|Keputusan yang boleh diambil, dikonsultasikan, atau dinaikkan sudah jelas.','Pelaksanaan wewenang ditinjau|Pelanggaran batas dan eskalasi yang tidak perlu dicatat serta dikoreksi.','Wewenang disempurnakan|Batas keputusan diperbarui dari risiko, kecepatan layanan, dan pengalaman kerja.']],
  governance_04: ['behavioral_maturity','multiple_role_priority',['Peran saling berebut waktu|Pemegang beberapa jabatan menentukan sendiri pekerjaan mana yang didahulukan.','Prioritas berubah karena desakan|Ada arahan sesekali, tetapi tugas mendesak selalu menggeser tugas penting.','Urutan tanggung jawab disepakati|Prioritas, porsi waktu, dan pihak pengganti untuk tiap peran sudah jelas.','Benturan peran dipantau|Pekerjaan tertunda dan beban berlebih ditinjau bersama atasan.','Susunan peran diperbaiki|Peran digabung, dipisah, atau dialihkan berdasarkan bukti beban dan hasil.']],
  governance_05: ['evidence_state','work_standard_availability',['Belum ada standar|Pekerjaan penting dilakukan berdasarkan ingatan atau kebiasaan masing-masing.','Sedang dirumuskan|Cara kerja mulai ditulis, tetapi belum lengkap atau belum disepakati.','Standar tersedia dan mudah dipahami|Langkah, tanggung jawab, dan hasil minimal pekerjaan penting sudah jelas.','Standar dipakai dan diperiksa|Pelaksanaan dibandingkan dengan standar dan penyimpangan ditindaklanjuti.','Standar diperbarui dari pengalaman|Dokumen kerja disempurnakan dari insiden, masukan, dan hasil review.']],
  governance_06: ['frequency','work_standard_use',['Tidak digunakan|Dokumen standar tersimpan tetapi pekerjaan berjalan dengan cara masing-masing.','Dipakai sesekali|Standar dibuka saat ada staf baru, audit, atau masalah tertentu.','Dipakai dalam pekerjaan rutin|Pelaksana menggunakan standar sebagai panduan kerja sehari-hari.','Kepatuhan dan kendala diperiksa|Atasan mengamati penggunaan standar dan memperbaiki hambatan penerapan.','Penggunaan menghasilkan perbaikan|Masukan pelaksana dipakai untuk menyederhanakan dan memperkuat standar.']],
  governance_07: ['behavioral_maturity','meeting_action_accountability',['Rapat berakhir tanpa tindak lanjut|Pembahasan selesai tanpa keputusan, penanggung jawab, atau batas waktu.','Tindak lanjut masih lisan|Ada kesepakatan, tetapi catatan dan pemantauannya tidak konsisten.','Keputusan dan PIC tercatat|Setiap tindakan penting memiliki penanggung jawab dan tenggat yang dipahami.','Kemajuan dibuka pada rapat berikutnya|Tindakan terlambat atau buntu dibahas dan mendapat keputusan lanjutan.','Mutu rapat terus diperbaiki|Agenda dan cara tindak lanjut dievaluasi dari tingkat penyelesaian keputusan.']],
  governance_08: ['behavioral_maturity','issue_escalation_clarity',['Semua masalah naik ke atas|Pelaksana cenderung menunggu atasan bahkan untuk masalah rutin.','Penyelesaian bergantung keberanian|Sebagian orang menangani sendiri, tetapi batas risiko belum jelas.','Tingkat penanganan dibedakan|Masalah rutin, lintas unit, dan berisiko memiliki jalur penyelesaian yang dipahami.','Eskalasi salah jalur diperiksa|Kasus terlambat, terlalu cepat naik, atau tidak dilaporkan ditinjau.','Jalur eskalasi disempurnakan|Ambang dan penanggung jawab diperbarui berdasarkan pola kasus nyata.']],
  governance_09: ['evidence_state','document_control',['Dokumen sulit ditemukan|Orang mencari melalui pesan pribadi atau memakai salinan yang belum tentu terbaru.','Tersimpan tetapi tersebar|Ada folder atau arsip, namun lokasi dan versi masih membingungkan.','Versi terbaru mudah diakses|Dokumen penting punya lokasi, nama, pemilik, dan versi yang jelas.','Akses dan versi diperiksa|Dokumen kadaluarsa, duplikat, dan hak akses ditinjau secara berkala.','Pengendalian dokumen diperbaiki|Struktur arsip dan masa simpan disesuaikan dari kebutuhan pengguna dan risiko.']],
  governance_10: ['extent','policy_change_adoption',['Pelaksana tidak mengetahui perubahan|Cara kerja lama tetap dipakai karena informasi tidak sampai.','Informasi sampai sebagian|Perubahan diumumkan, tetapi pemahaman dan waktu penerapan berbeda antarorang.','Perubahan dipahami pihak terkait|Pelaksana mengetahui apa yang berubah, alasan, dan mulai kapan berlaku.','Penerapan perubahan diperiksa|Kesalahan penerapan dan pertanyaan dikumpulkan lalu ditindaklanjuti.','Adopsi perubahan dievaluasi|Cara sosialisasi dan dukungan diperbaiki dari hasil penerapan.']],

  people_01: ['behavioral_maturity','workforce_planning',['Personil mengikuti kebiasaan|Jumlah dan jenis tenaga tidak dihitung dari pekerjaan yang perlu diselesaikan.','Kebutuhan diperkirakan kasar|Penambahan orang dilakukan saat beban terasa berat tanpa pemetaan tugas.','Kebutuhan dihitung dari layanan|Volume kerja, jadwal, dan kompetensi menjadi dasar kebutuhan personil.','Kesenjangan personil ditinjau|Kekurangan, kelebihan, dan salah penempatan dipantau serta ditindaklanjuti.','Rencana tenaga diperbarui|Proyeksi personil disesuaikan dengan perubahan program dan produktivitas.']],
  people_02: ['behavioral_maturity','selection_role_fit',['Memilih berdasarkan kedekatan|Rekrutmen atau penempatan belum memakai kriteria tugas yang jelas.','Kriteria masih umum|Pendidikan atau pengalaman dilihat, tetapi kemampuan kerja belum diuji konsisten.','Kriteria sesuai jabatan|Persyaratan, proses seleksi, dan keputusan penempatan terkait langsung dengan tugas.','Kecocokan setelah masuk diperiksa|Kinerja masa awal dinilai untuk mengoreksi seleksi atau penempatan.','Metode seleksi disempurnakan|Kriteria dan cara uji diperbarui dari keberhasilan personil sebelumnya.']],
  people_03: ['extent','employee_onboarding',['Langsung bekerja sendiri|Personil baru tidak menerima penjelasan terarah tentang tugas dan aturan penting.','Mendapat penjelasan terbatas|Atasan menjelaskan secara lisan, tetapi isi berbeda antarunit.','Orientasi dasar lengkap|Tugas, standar, risiko, dan orang yang dapat membantu dijelaskan sejak awal.','Pemahaman awal diperiksa|Atasan mengecek praktik kerja dan menutup kesenjangan selama masa orientasi.','Orientasi diperbaiki dari pengalaman|Materi dan pendampingan diperbarui berdasarkan masalah personil baru.']],
  people_04: ['behavioral_maturity','competency_development',['Pelatihan mengikuti kesempatan|Kegiatan pengembangan dipilih karena tersedia, bukan dari kebutuhan pekerjaan.','Kebutuhan diketahui informal|Atasan mengenali beberapa kekurangan, tetapi tindak lanjut belum terencana.','Kebutuhan dan rencana jelas|Kesenjangan kemampuan dipetakan dan memiliki tindakan pengembangan yang sesuai.','Dampak pengembangan diperiksa|Perubahan kemampuan dan penerapan setelah pelatihan dinilai oleh atasan.','Pengembangan diarahkan ke masa depan|Rencana kompetensi diperbarui dari strategi dan kebutuhan peran berikutnya.']],
  people_05: ['extent','workload_balance',['Beban sangat timpang|Sebagian orang terus kewalahan sementara kapasitas orang lain tidak terlihat.','Ketimpangan baru dibahas saat krisis|Beban diketahui, tetapi penyeimbangan hanya sementara.','Beban dan kapasitas dipetakan|Tugas, volume, waktu, dan kemampuan menjadi dasar pembagian kerja.','Ketimpangan dipantau|Lembur, antrean, kesalahan, dan kelelahan ditinjau untuk mengatur ulang tugas.','Kapasitas dioptimalkan|Proses, jadwal, dan susunan tim diperbaiki berdasarkan pola beban.']],
  people_06: ['behavioral_maturity','workforce_resilience',['Tidak ada pengganti|Pekerjaan berhenti atau orang terus bekerja saat sakit dan beban tinggi.','Bantuan bersifat spontan|Rekan membantu ketika diminta, tetapi tugas penting belum punya cadangan.','Istirahat dan backup diatur|Jadwal, penyerahan tugas, dan orang pengganti untuk pekerjaan penting sudah jelas.','Kesiapan backup diperiksa|Kemampuan pengganti dan kejadian beban berlebih ditinjau serta diperbaiki.','Ketahanan tim ditingkatkan|Rotasi, lintas keterampilan, dan kapasitas cadangan direncanakan dari pola kebutuhan.']],
  people_07: ['extent','performance_expectation',['Hasil kerja tidak dijelaskan|Personil hanya menerima daftar tugas tanpa ukuran hasil yang diharapkan.','Harapan bergantung atasan|Sebagian orang mendapat target, tetapi ukuran berbeda dan mudah berubah.','Hasil utama dan ukuran jelas|Personil memahami keluaran, mutu, dan waktu yang diharapkan dari perannya.','Pencapaian dibahas berkala|Atasan menggunakan ukuran tersebut untuk membahas kemajuan dan kendala.','Ekspektasi diperbarui|Ukuran hasil disesuaikan dari strategi, kapasitas, dan mutu layanan.']],
  people_08: ['frequency','performance_review',['Tidak pernah dievaluasi|Kinerja dibahas hanya ketika terjadi kesalahan besar atau konflik.','Evaluasi tidak teratur|Ada penilaian sesekali, tetapi ukuran dan catatannya berubah-ubah.','Evaluasi rutin dengan ukuran jelas|Hasil kerja dibahas pada jadwal dan bukti yang disepakati.','Kualitas evaluasi diperiksa|Konsistensi penilai, ketepatan bukti, dan tindak lanjut ditinjau.','Sistem evaluasi disempurnakan|Ukuran dan proses diperbaiki berdasarkan dampaknya pada kinerja.']],
  people_09: ['behavioral_maturity','performance_coaching',['Hanya menerima teguran|Setelah evaluasi, personil tidak mendapat arahan perbaikan yang dapat dilakukan.','Umpan balik tergantung atasan|Sebagian menerima saran, tetapi dukungan dan tindak lanjut belum pasti.','Umpan balik dan rencana perbaikan jelas|Kekuatan, kesenjangan, tindakan, dan dukungan dibahas bersama.','Kemajuan perbaikan ditinjau|Atasan mengecek praktik baru dan membantu mengatasi hambatan.','Coaching diperbaiki dari hasil|Cara pendampingan disesuaikan berdasarkan perkembangan personil.']],
  people_10: ['behavioral_maturity','employment_lifecycle_control',['Ketentuan tidak jelas|Penghargaan, kompensasi, atau serah terima bergantung keputusan kasus per kasus.','Ada kebiasaan tetapi tidak konsisten|Sebagian aturan dipahami, namun penerapan dan catatan berbeda.','Ketentuan dan alur terdokumentasi|Dasar keputusan, persetujuan, serta serah terima tugas sudah jelas.','Penerapan ditinjau|Ketidakwajaran, keterlambatan, dan pekerjaan yang tertinggal diperiksa.','Sistem diperbarui secara adil|Ketentuan disempurnakan dari data, kemampuan lembaga, dan umpan balik.']],

  education_01: ['behavioral_maturity','learning_objective_clarity',['Tujuan belum dinyatakan|Program berjalan dari daftar materi tanpa hasil belajar yang jelas.','Tujuan masih umum|Ada harapan belajar, tetapi sulit dipakai memilih materi atau penilaian.','Tujuan belajar konkret|Kemampuan yang perlu ditunjukkan santri sudah jelas dan dipahami guru.','Capaian tujuan diperiksa|Hasil santri dibandingkan dengan tujuan dan kesenjangannya ditindaklanjuti.','Tujuan diperbarui|Rumusan tujuan disempurnakan dari hasil belajar dan kebutuhan santri.']],
  education_02: ['evidence_state','learning_sequence',['Urutan belum ada|Materi ditentukan masing-masing guru tanpa jenjang yang disepakati.','Urutan sedang disusun|Sebagian materi sudah berjenjang, tetapi perpindahan antartingkat belum jelas.','Urutan dan prasyarat tersedia|Materi, level, dan kemampuan prasyarat tersusun serta dipakai guru.','Kelancaran jenjang diperiksa|Pengulangan, lompatan, dan hambatan perpindahan level ditinjau.','Urutan diperbaiki dari hasil|Susunan materi diperbarui berdasarkan pola penguasaan santri.']],
  education_03: ['extent','learning_resource_readiness',['Sering disiapkan mendadak|Jadwal, guru, atau bahan baru dicari saat program akan berjalan.','Sebagian kebutuhan siap|Komponen utama ada, tetapi kekurangan masih sering mengganggu pembelajaran.','Kebutuhan program tersedia|Jadwal, guru, ruang, dan sumber belajar sesuai rencana program.','Kesiapan dipantau|Benturan jadwal, kekurangan guru, dan bahan dicatat lalu diselesaikan.','Kapasitas disesuaikan|Sumber daya direncanakan ulang dari jumlah santri dan hasil program.']],
  education_04: ['behavioral_maturity','lesson_preparation',['Mengajar dari kebiasaan|Guru masuk kelas tanpa rencana yang mengaitkan kemampuan santri dan tujuan.','Persiapan berbeda antar guru|Sebagian guru membuat rencana, tetapi kedalaman dan penggunaannya belum konsisten.','Rencana sesuai tujuan dan santri|Kegiatan, materi, serta bantuan disiapkan dari tujuan dan kondisi kelas.','Pelaksanaan rencana direfleksi|Guru menilai bagian yang berhasil atau perlu diubah setelah mengajar.','Persiapan berkembang kolaboratif|Guru berbagi bukti belajar untuk memperbaiki rancangan berikutnya.']],
  education_05: ['frequency','active_learning',['Santri hanya menerima|Pembelajaran didominasi penjelasan tanpa kesempatan mengolah atau mencoba.','Aktif pada kegiatan tertentu|Diskusi atau praktik muncul sesekali dan belum terkait jelas dengan tujuan.','Santri rutin mengolah pemahaman|Mereka bertanya, berdiskusi, mencoba, dan menjelaskan kembali materi.','Keterlibatan diperiksa|Guru mengamati siapa yang belum terlibat atau belum memahami lalu menyesuaikan.','Strategi aktif disempurnakan|Metode dipilih dari bukti pemahaman, bukan sekadar variasi kegiatan.']],
  education_06: ['behavioral_maturity','learning_barrier_followup',['Tidak ditindaklanjuti|Ketidakhadiran atau kesulitan belajar hanya dicatat atau dibiarkan.','Ditangani jika sudah berat|Guru memberi bantuan setelah masalah berulang atau wali mengeluh.','Hambatan terdeteksi dan ditangani|Ada pemantauan, kontak, bantuan, serta penanggung jawab yang jelas.','Hasil bantuan diperiksa|Kehadiran dan perkembangan setelah tindakan dipantau.','Pola hambatan dicegah|Data kasus dipakai memperbaiki jadwal, dukungan, dan cara belajar.']],
  education_07: ['evidence_state','assessment_traceability',['Kriteria tidak jelas|Nilai sulit dijelaskan karena dasar penilaian dan buktinya tidak tersimpan.','Kriteria tersedia sebagian|Beberapa tugas memakai rubrik, tetapi penerapannya berbeda antar guru.','Kriteria dan bukti dapat ditelusuri|Santri dinilai dengan ukuran yang jelas dan hasil kerjanya tersimpan.','Konsistensi penilaian diperiksa|Perbedaan antarpenilai dan kualitas bukti ditinjau.','Sistem penilaian diperbaiki|Kriteria diperbarui dari kesesuaian tujuan dan pola hasil santri.']],
  education_08: ['behavioral_maturity','assessment_followup',['Nilai berhenti sebagai laporan|Hasil penilaian tidak mengubah bantuan atau kegiatan belajar berikutnya.','Tindak lanjut tergantung guru|Sebagian santri mendapat remedial, tetapi kriteria dan caranya berbeda.','Bantuan sesuai kebutuhan|Remedial, pengayaan, atau dukungan diberikan dari kesenjangan yang terlihat.','Kemajuan setelah bantuan diperiksa|Santri dinilai kembali untuk memastikan kebutuhan tertangani.','Pola tindak lanjut disempurnakan|Efektivitas berbagai bantuan dibandingkan untuk memperbaiki pembelajaran.']],
  education_09: ['frequency','program_quality_review',['Hanya menghitung kegiatan|Keberhasilan dinilai dari jumlah kelas atau acara yang terlaksana.','Mutu dibahas saat ada masalah|Review dilakukan setelah keluhan atau hasil yang mengecewakan.','Mutu program ditinjau berkala|Tujuan, pengalaman belajar, hasil santri, dan kendala dibahas bersama.','Review menghasilkan perbaikan|Keputusan, PIC, dan tenggat perubahan program dicatat dan dipantau.','Dampak perubahan dibandingkan|Program dikembangkan berdasarkan bukti sebelum dan sesudah perbaikan.']],
  education_10: ['behavioral_maturity','progression_criteria',['Kenaikan berdasarkan kebiasaan|Santri naik terutama karena waktu belajar atau keputusan individual.','Ada syarat tidak seragam|Beberapa kemampuan dipertimbangkan, tetapi kriteria berbeda antar kelas.','Kriteria kenaikan jelas|Kemampuan minimal, bukti, dan pihak yang memutuskan sudah disepakati.','Keputusan kenaikan ditinjau|Konsistensi keputusan dan perkembangan setelah naik diperiksa.','Kriteria diperbaiki|Syarat kenaikan disesuaikan dari keberhasilan santri di level berikutnya.']],

  care_01: ['behavioral_maturity','student_program_accountability',['Kegiatan mengikuti jadwal lama|Program harian berjalan tanpa tujuan perkembangan atau penanggung jawab yang tegas.','Tujuan ada pada sebagian kegiatan|Beberapa kegiatan jelas arahnya, lainnya hanya mengisi waktu.','Tujuan dan PIC jelas|Setiap program penting memiliki hasil yang diharapkan dan penanggung jawab.','Pelaksanaan diperiksa|Kehadiran, mutu, dan kendala program ditinjau serta ditindaklanjuti.','Program diperbaiki dari perkembangan|Kegiatan disesuaikan berdasarkan kebutuhan dan perubahan perilaku santri.']],
  care_02: ['evidence_state','student_program_record',['Catatan tidak tersedia|Kehadiran dan pelaksanaan program bergantung ingatan pendamping.','Catatan tidak lengkap|Sebagian kegiatan dicatat, tetapi format dan ketepatannya berbeda.','Catatan rutin tersedia|Kehadiran, pelaksanaan, dan kejadian penting tercatat serta mudah ditemukan.','Kualitas catatan diperiksa|Kelengkapan, keterlambatan, dan tindak lanjut catatan ditinjau.','Catatan dipakai memperbaiki program|Pola kehadiran dan pelaksanaan menjadi dasar perubahan kegiatan.']],
  care_03: ['extent','student_support_contact',['Santri tidak tahu harus ke siapa|Permintaan bantuan bergantung pada siapa yang kebetulan ditemui.','Hanya sebagian santri tahu|Pendamping dikenal di beberapa kelompok, tetapi akses tidak merata.','Setiap santri punya pendamping jelas|Nama, cara menghubungi, dan waktu bantuan dipahami santri.','Akses pendamping diperiksa|Santri yang tidak terjangkau atau enggan meminta bantuan ditindaklanjuti.','Sistem pendampingan diperkuat|Rasio, jadwal, dan cara kontak disesuaikan dari pola kebutuhan.']],
  care_04: ['frequency','character_coaching',['Tidak ada pembinaan terjadwal|Pembinaan hanya berupa teguran ketika terjadi pelanggaran.','Berjalan sesekali|Ada pertemuan pembinaan, tetapi isi dan tindak lanjutnya tidak konsisten.','Pembinaan rutin dan terarah|Santri berdialog tentang kebiasaan, nilai, dan tujuan perkembangan.','Perkembangan setelah pembinaan diperiksa|Pendamping mencatat kebutuhan dan memantau perubahan perilaku.','Pendekatan pembinaan disempurnakan|Metode diperbaiki dari pola perkembangan dan umpan balik santri.']],
  care_05: ['behavioral_maturity','case_handling_boundary',['Semua kasus ditangani pendamping harian|Masalah khusus ditangani tanpa batas kompetensi atau jalur rujukan.','Rujukan bergantung inisiatif|Pendamping kadang meminta bantuan, tetapi tanda dan pihak tujuan belum jelas.','Batas tugas dan rujukan jelas|Kasus rutin, sensitif, kesehatan, dan perlindungan memiliki penangan yang tepat.','Kepatuhan rujukan diperiksa|Kasus terlambat atau salah tangani ditinjau dan dikoreksi.','Jalur kasus diperbarui|Batas dan jaringan specialist diperbaiki dari pengalaman penanganan.']],
  care_06: ['behavioral_maturity','educative_discipline',['Aturan bergantung petugas|Pelanggaran serupa dapat menerima tindakan berbeda tanpa alasan jelas.','Aturan ada tetapi tidak konsisten|Santri mengenal aturan, namun penerapan dan tujuan mendidiknya berubah-ubah.','Aturan konsisten dan mendidik|Konsekuensi proporsional, dijelaskan, dan diarahkan pada perbaikan perilaku.','Dampak disiplin ditinjau|Pengulangan, ketidakadilan, dan efek pada santri dipantau.','Pendekatan diperbaiki|Aturan dan pembinaan diperbarui berdasarkan keselamatan dan hasil perkembangan.']],
  care_07: ['behavioral_maturity','incident_reporting',['Pelaporan tidak jelas|Masalah disimpan sendiri atau disampaikan melalui jalur informal.','Jalur dikenal sebagian orang|Ada pihak tujuan, tetapi jenis kasus dan waktu pelaporan belum jelas.','Jalur dan respons ditetapkan|Pelapor tahu kepada siapa, bagaimana, dan kapan masalah harus dinaikkan.','Pelaporan dipantau|Keterlambatan, keamanan pelapor, dan tindak lanjut kasus diperiksa.','Sistem pelaporan diperkuat|Jalur disempurnakan dari pola kasus dan pengalaman pengguna.']],
  care_08: ['extent','safe_help_seeking',['Tidak ada kanal aman|Santri khawatir cerita tersebar atau menimbulkan hukuman.','Ada orang tepercaya secara informal|Sebagian santri punya tempat bercerita, tetapi tidak semua terlindungi.','Kanal aman diketahui|Santri memiliki beberapa cara meminta bantuan dengan privasi dan respons yang jelas.','Keamanan kanal diuji|Akses, kerahasiaan, dan pengalaman santri dipantau.','Kanal diperbaiki bersama santri|Masukan dan pola penggunaan menjadi dasar memperkuat perlindungan.']],
  care_09: ['frequency','student_development_monitoring',['Tidak dipantau terarah|Perkembangan karakter hanya dinilai dari kesan umum atau pelanggaran.','Dicatat pada kasus tertentu|Pendamping membuat catatan ketika ada masalah menonjol.','Perkembangan ditinjau berkala|Kebiasaan, kekuatan, dan kebutuhan santri dibahas dengan bukti sederhana.','Tindak lanjut perkembangan diperiksa|Rencana pendampingan dan perubahan setelahnya dipantau.','Pemantauan disempurnakan|Indikator dan cara pendampingan diperbaiki dari pola perkembangan.']],
  care_10: ['behavioral_maturity','special_support_coordination',['Dukungan berjalan sendiri-sendiri|Guru, pengasuh, kesehatan, dan wali tidak berbagi rencana yang sama.','Koordinasi terjadi saat krisis|Pihak terkait berkumpul setelah kebutuhan menjadi berat.','Rencana dukungan terkoordinasi|Kebutuhan, peran, batas informasi, dan penanggung jawab sudah disepakati.','Kemajuan dukungan diperiksa|Pihak terkait menilai perubahan dan menyesuaikan tindakan.','Koordinasi diperkuat|Cara kerja lintas pihak diperbaiki dari hasil dan kebutuhan santri.']],

  operations_01: ['behavioral_maturity','food_service_control',['Layanan berjalan harian|Menu, belanja, dan pembagian tugas ditentukan mendadak.','Sebagian unsur direncanakan|Jadwal atau PIC ada, tetapi standar porsi dan mutu belum konsisten.','Rencana dan standar lengkap|Menu, jumlah, mutu, waktu, dan penanggung jawab sudah jelas.','Pelaksanaan layanan diperiksa|Sisa, keterlambatan, keluhan, dan penyimpangan ditindaklanjuti.','Layanan diperbaiki berbasis data|Perencanaan diubah dari konsumsi, gizi, biaya, dan umpan balik.']],
  operations_02: ['behavioral_maturity','food_safety',['Penanganan bergantung kebiasaan|Penerimaan, penyimpanan, dan kebersihan bahan tidak punya pemeriksaan tetap.','Kontrol dilakukan sebagian|Kondisi bahan atau kebersihan dicek, tetapi catatan dan konsistensinya lemah.','Kontrol keamanan pangan berjalan|Kualitas penerimaan, suhu, penyimpanan, kebersihan, dan kedaluwarsa diperiksa.','Penyimpangan ditindaklanjuti|Temuan bahan rusak atau praktik tidak aman dicatat dan diperbaiki.','Pencegahan terus diperkuat|Kontrol diperbarui dari insiden, audit, dan perubahan kebutuhan.']],
  operations_03: ['extent','healthcare_access',['Akses tidak pasti|Santri bergantung pada petugas yang kebetulan tersedia.','Pertolongan dasar terbatas|Ada bantuan, tetapi waktu layanan dan jalur rujukan belum jelas.','Akses dan rujukan jelas|Santri tahu cara mendapat pertolongan dan kapan dirujuk.','Kecepatan dan hasil diperiksa|Keterlambatan, pengulangan keluhan, dan tindak lanjut rujukan dipantau.','Layanan disesuaikan|Kapasitas dan jejaring rujukan diperbaiki dari pola kebutuhan kesehatan.']],
  operations_04: ['evidence_state','health_supply_record',['Belum tertata|Obat, stok, dan catatan layanan mudah tercecer atau tidak terpantau.','Daftar tersedia sebagian|Stok dicatat sesekali dan riwayat layanan belum lengkap.','Stok dan layanan tercatat|Penerimaan, penggunaan, kedaluwarsa, serta layanan dapat ditelusuri.','Catatan dan stok diperiksa|Selisih, kekosongan, dan penggunaan tidak wajar ditindaklanjuti.','Pengelolaan dioptimalkan|Kebutuhan stok dan format catatan diperbaiki dari pola pemakaian.']],
  operations_05: ['behavioral_maturity','sanitation_accountability',['Tanggung jawab tidak jelas|Kebersihan dan sanitasi dikerjakan ketika terlihat kotor atau ada keluhan.','Ada pembagian informal|Orang tertentu biasa menangani, tetapi area dan standar belum lengkap.','Area, standar, dan PIC jelas|Air, toilet, kebersihan, jadwal, dan penanggung jawab ditetapkan.','Kondisi sanitasi diperiksa|Temuan risiko, ketidakpatuhan, dan keluhan ditindaklanjuti.','Pencegahan diperkuat|Standar dan sumber daya diperbaiki dari inspeksi dan kejadian kesehatan.']],
  operations_06: ['behavioral_maturity','utility_continuity',['Menunggu gangguan terjadi|Penanganan air atau listrik dimulai tanpa rencana saat layanan berhenti.','Ada kontak darurat informal|Orang tertentu tahu harus berbuat apa, tetapi alternatif belum siap.','Prosedur dan alternatif jelas|Kontak, prioritas layanan, sumber cadangan, dan komunikasi sudah disiapkan.','Kesiapan diuji|Respons gangguan dicatat atau disimulasikan dan kekurangannya diperbaiki.','Ketahanan layanan ditingkatkan|Kapasitas cadangan diperbarui dari frekuensi dan dampak gangguan.']],
  operations_07: ['evidence_state','asset_accountability',['Aset tidak terdaftar|Keberadaan, kondisi, dan pemegang aset penting sulit dipastikan.','Daftar belum lengkap|Sebagian aset tercatat, tetapi lokasi atau kondisinya jarang diperbarui.','Register aset tersedia|Identitas, lokasi, kondisi, dan penanggung jawab aset penting tercatat.','Register diverifikasi|Pemeriksaan fisik, selisih, dan kondisi rusak ditindaklanjuti.','Keputusan aset berbasis riwayat|Pengadaan, pemeliharaan, dan penggantian memakai data umur dan biaya.']],
  operations_08: ['behavioral_maturity','maintenance_followthrough',['Perbaikan menunggu keluhan berulang|Permintaan disampaikan lisan dan mudah terlupakan.','Permintaan dicatat sebagian|Ada daftar, tetapi prioritas, PIC, dan status belum jelas.','Alur perbaikan dapat dilacak|Permintaan, risiko, penanggung jawab, target, dan penyelesaian tercatat.','Mutu penyelesaian diperiksa|Keterlambatan dan kerusakan berulang ditinjau.','Pemeliharaan menjadi preventif|Riwayat kerusakan dipakai menjadwalkan perawatan sebelum gagal.']],
  operations_09: ['behavioral_maturity','physical_security',['Akses terbuka tanpa kontrol|Orang dan kendaraan dapat masuk tanpa pemeriksaan yang memadai.','Kontrol hanya di waktu tertentu|Penjagaan ada, tetapi area, kunjungan, dan kejadian tidak dikelola konsisten.','Akses dan risiko dikendalikan|Area terbatas, identitas pengunjung, izin, serta respons insiden sudah jelas.','Kontrol keamanan diperiksa|Pelanggaran akses dan titik rawan ditinjau serta diperbaiki.','Keamanan disesuaikan berbasis risiko|Kontrol diperbarui dari insiden, perubahan fasilitas, dan aktivitas.']],
  operations_10: ['behavioral_maturity','emergency_preparedness',['Belum siap|Peran, kontak, jalur evakuasi, dan perlengkapan darurat belum jelas.','Ada perlengkapan atau arahan sebagian|Kesiapan bergantung beberapa orang dan belum pernah diuji.','Rencana darurat lengkap|Skenario utama, komando, komunikasi, evakuasi, dan kebutuhan khusus ditetapkan.','Latihan dan temuan ditindaklanjuti|Kesiapan diuji dan kekurangan memiliki PIC serta tenggat.','Rencana terus diperbarui|Pelajaran latihan dan perubahan risiko masuk ke prosedur berikutnya.']],

  finance_01: ['evidence_state','institutional_document_control',['Dokumen tersebar|Berkas penting tersimpan pada orang atau tempat berbeda tanpa daftar.','Arsip mulai dihimpun|Sebagian berkas terkelompok, tetapi pemilik dan kelengkapannya belum jelas.','Arsip dan penjaga jelas|Daftar, lokasi, akses, serta penanggung jawab dokumen tersedia.','Kelengkapan arsip diperiksa|Berkas hilang, ganda, atau tidak sah ditindaklanjuti.','Tata arsip disempurnakan|Masa simpan dan perlindungan diperbarui dari kebutuhan serta risiko.']],
  finance_02: ['frequency','document_validity_monitoring',['Tidak dipantau|Pembaruan dilakukan setelah dokumen kedaluwarsa atau diminta pihak lain.','Dicek menjelang kebutuhan|Masa berlaku diingat orang tertentu tanpa kalender bersama.','Jadwal pembaruan tersedia|Tanggal, syarat, PIC, dan pengingat setiap dokumen penting tercatat.','Keterlambatan ditinjau|Status pembaruan dan hambatan diperiksa sebelum masa berlaku habis.','Proses pembaruan diperbaiki|Waktu mulai dan dokumen pendukung disesuaikan dari pengalaman.']],
  finance_03: ['behavioral_maturity','priority_based_budgeting',['Anggaran mengikuti tahun lalu|Alokasi diteruskan tanpa menguji kaitannya dengan prioritas program.','Prioritas dipertimbangkan sebagian|Program utama mendapat perhatian, tetapi dasar angka belum jelas.','Anggaran terkait rencana kerja|Setiap alokasi besar memiliki tujuan, kebutuhan, dan hasil yang diharapkan.','Realisasi dan hasil ditinjau|Selisih anggaran dibahas bersama kemajuan program.','Alokasi diperbaiki berbasis manfaat|Dana dipindahkan berdasarkan hasil, risiko, dan kebutuhan terbaru.']],
  finance_04: ['evidence_state','budget_change_control',['Perubahan tidak tercatat|Anggaran bergeser melalui keputusan lisan tanpa jejak persetujuan.','Catatan tidak lengkap|Perubahan besar dicatat, tetapi alasan atau pemberi persetujuan sering hilang.','Perubahan dapat ditelusuri|Nilai, alasan, dampak, dan persetujuan tercatat sebelum digunakan.','Pola perubahan ditinjau|Frekuensi dan penyebab deviasi dibahas untuk memperbaiki perencanaan.','Kontrol disempurnakan|Batas persetujuan diperbarui dari risiko dan pengalaman realisasi.']],
  finance_05: ['evidence_state','transaction_traceability',['Bukti sulit ditelusuri|Catatan dan bukti transaksi tidak berpasangan atau tersimpan pribadi.','Sebagian transaksi lengkap|Bukti tersedia untuk transaksi tertentu, tetapi kode dan arsip belum konsisten.','Setiap transaksi terlacak|Tanggal, tujuan, pihak, akun, persetujuan, dan bukti saling terhubung.','Kelengkapan diperiksa|Transaksi tanpa bukti, terlambat, atau tidak wajar ditindaklanjuti.','Pencatatan dioptimalkan|Format dan alur diperbaiki untuk mengurangi kesalahan dan waktu pencarian.']],
  finance_06: ['behavioral_maturity','financial_control',['Satu orang menguasai seluruh proses|Transaksi penting dapat dibuat, disetujui, dan dicatat oleh orang yang sama.','Pemeriksaan bersifat informal|Orang lain kadang melihat, tetapi bukti dan batas transaksi belum jelas.','Kontrol pihak kedua berjalan|Persetujuan, verifikasi, atau rekonsiliasi independen diterapkan sesuai risiko.','Efektivitas kontrol diperiksa|Pengecualian dan transaksi lolos ditinjau serta dikoreksi.','Kontrol disesuaikan berbasis risiko|Pemisahan atau kontrol pengganti diperbarui dari pola temuan.']],
  finance_07: ['frequency','financial_reconciliation',['Tidak pernah dicocokkan|Selisih baru diketahui saat dana kurang atau laporan diminta.','Dicocokkan tidak teratur|Pemeriksaan dilakukan sesekali tanpa bukti penyelesaian selisih.','Rekonsiliasi rutin|Saldo kas, bank, dan catatan dicocokkan pada jadwal tetap.','Selisih ditutup sampai jelas|Penyebab, koreksi, penanggung jawab, dan waktu penyelesaian tercatat.','Pola selisih dicegah|Temuan berulang digunakan memperbaiki proses transaksi.']],
  finance_08: ['behavioral_maturity','financial_review',['Laporan hanya disimpan|Angka disusun untuk kewajiban administrasi dan tidak dibahas.','Ditelaah saat ada kebutuhan|Pimpinan melihat laporan ketika kas menipis atau ada permintaan.','Laporan dibahas berkala|Realisasi, posisi kas, kewajiban, dan penyimpangan menjadi bahan keputusan.','Keputusan keuangan dipantau|Tindak lanjut review memiliki PIC dan hasilnya diperiksa.','Analisis diperkuat|Tren dan proyeksi dipakai untuk memperbaiki keputusan periode berikutnya.']],
  finance_09: ['behavioral_maturity','procurement_control',['Pembelian langsung oleh peminta|Kebutuhan, persetujuan, pembelian, dan penerimaan tidak dibedakan.','Alur ada untuk sebagian belanja|Pembelian besar lebih tertib, tetapi penerimaan dan bukti belum konsisten.','Tahap pembelian jelas|Permintaan, persetujuan, pemilihan, pembelian, dan penerimaan dapat ditelusuri.','Kepatuhan dan hasil diperiksa|Selisih barang, harga, kualitas, dan keterlambatan ditindaklanjuti.','Pengadaan diperbaiki|Data pemasok dan pemakaian dipakai meningkatkan nilai serta keandalan.']],
  finance_10: ['behavioral_maturity','fund_accountability',['Pertanggungjawaban bergantung kepercayaan|Dana selesai dianggap aman tanpa laporan atau pemeriksaan kepentingan terkait.','Bukti diminta tidak konsisten|Sebagian pengeluaran dilaporkan, tetapi tenggat dan konflik belum jelas.','Aturan pertanggungjawaban jelas|Bukti, tenggat, sisa dana, dan pengungkapan konflik diterapkan.','Pengecualian ditinjau|Keterlambatan, kekurangan bukti, dan transaksi pihak terkait diperiksa.','Integritas sistem diperkuat|Aturan diperbarui dari temuan, risiko, dan pola hubungan pihak terkait.']],

  parents_01: ['extent','parent_information_clarity',['Informasi sering tidak lengkap|Wali mengetahui program, biaya, atau aturan dari kabar yang berbeda-beda.','Informasi tersedia sebagian|Pengumuman ada, tetapi rincian dan versi terbarunya sulit dipastikan.','Informasi utama jelas|Program, biaya, aturan, waktu, dan kontak disampaikan melalui sumber resmi.','Pemahaman wali diperiksa|Pertanyaan berulang dan salah tafsir ditindaklanjuti dengan perbaikan informasi.','Informasi terus disederhanakan|Isi dan kanal diperbarui dari kebutuhan serta pengalaman wali.']],
  parents_02: ['evidence_state','parent_onboarding',['Belum ada orientasi|Wali baru mencari sendiri aturan dan cara mendapatkan layanan.','Penjelasan bersifat informal|Sebagian wali mendapat arahan, tetapi isi berbeda menurut petugas.','Orientasi wali tersedia|Hak, kewajiban, layanan, kontak, dan aturan penting dijelaskan sejak awal.','Pemahaman setelah orientasi diperiksa|Kebingungan dan kebutuhan wali baru dikumpulkan serta ditindaklanjuti.','Orientasi diperbaiki|Materi dan cara penyampaian disesuaikan dari pengalaman angkatan sebelumnya.']],
  parents_03: ['behavioral_maturity','service_channel_clarity',['Semua pertanyaan masuk ke satu orang|Wali tidak tahu kanal yang tepat untuk kebutuhan berbeda.','Kanal dikenal dari kebiasaan|Sebagian wali tahu kontak tertentu, tetapi pembagian layanan belum resmi.','Kanal per layanan jelas|Akademik, pengasuhan, izin, kesehatan, dan administrasi punya jalur yang dipahami.','Ketepatan rujukan diperiksa|Pesan salah alamat dan waktu pemindahan ditinjau.','Kanal dioptimalkan|Pembagian dan akses diperbarui dari volume serta jenis pertanyaan.']],
  parents_04: ['behavioral_maturity','parent_request_resolution',['Pesan mudah berhenti|Permintaan diterima tetapi tidak ada pemilik atau status penyelesaian.','Diteruskan secara pribadi|Petugas menghubungi orang yang dianggap tepat tanpa pelacakan.','Permintaan punya PIC dan jawaban|Penerimaan, penerusan, batas waktu, dan respons dapat diketahui.','Penyelesaian diperiksa|Pesan terlambat dan jawaban tidak tuntas ditindaklanjuti.','Alur diperbaiki dari pola layanan|Jenis permintaan dan waktu respons dipakai menyederhanakan proses.']],
  parents_05: ['frequency','student_progress_reporting',['Tidak ada laporan teratur|Wali mengetahui perkembangan hanya ketika ada masalah atau bertanya.','Laporan diberikan sesekali|Isi dan waktu berbeda menurut unit atau wali.','Laporan rutin dan bermakna|Wali menerima kemajuan, kebutuhan, dan dukungan yang dapat dilakukan.','Mutu laporan diperiksa|Ketepatan, konsistensi, dan kegunaan laporan ditinjau.','Pelaporan disempurnakan|Isi dan periode diperbarui dari perkembangan santri dan kebutuhan wali.']],
  parents_06: ['extent','parent_report_clarification',['Tidak ada ruang klarifikasi|Wali menerima laporan tanpa tahu kepada siapa harus bertanya.','Klarifikasi melalui hubungan pribadi|Sebagian wali dapat bertanya, tetapi akses dan respons tidak merata.','Jalur klarifikasi jelas|Wali tahu waktu, kanal, dan pihak yang dapat menjelaskan laporan.','Pertanyaan ditindaklanjuti|Kebingungan berulang dan komitmen lanjutan dicatat.','Dialog diperbaiki|Format laporan dan mekanisme klarifikasi disesuaikan dari pola pertanyaan.']],
  parents_07: ['behavioral_maturity','parent_service_flow',['Alur berbeda tiap petugas|Izin, kunjungan, dan titipan diproses berdasarkan kebiasaan orang yang menerima.','Syarat diketahui sebagian|Ada aturan, tetapi langkah, waktu, dan status belum jelas.','Alur layanan mudah dipahami|Syarat, kanal, PIC, waktu, dan hasil setiap layanan tersedia.','Pelaksanaan layanan dipantau|Antrean, penolakan, keterlambatan, dan pengecualian ditinjau.','Layanan disederhanakan|Langkah diperbaiki dari kebutuhan wali dan risiko santri.']],
  parents_08: ['behavioral_maturity','complaint_resolution',['Keluhan tidak tercatat|Penyelesaian bergantung percakapan dan sulit dipastikan akhirnya.','Sebagian keluhan dicatat|Kasus besar ditangani, tetapi PIC dan konfirmasi belum konsisten.','Keluhan terlacak sampai selesai|Isi, klasifikasi, PIC, tindakan, waktu, dan konfirmasi tercatat.','Keadilan penyelesaian diperiksa|Keterlambatan, pengulangan, dan perbedaan perlakuan ditinjau.','Keluhan mendorong perbaikan|Pola kasus dipakai memperbaiki layanan dan komunikasi.']],
  parents_09: ['behavioral_maturity','parent_education_partnership',['Pelibatan sebatas informasi|Wali diminta hadir atau membayar tanpa arah dukungan pendidikan yang jelas.','Kegiatan dilakukan sesekali|Ada parenting atau ajakan, tetapi tidak terkait kebutuhan santri.','Peran wali diarahkan|Wali mendapat panduan konkret yang selaras dengan tujuan perkembangan santri.','Kontribusi dan kendala ditinjau|Pesantren melihat partisipasi serta hambatan wali.','Kemitraan disesuaikan|Bentuk dukungan diperbaiki dari kebutuhan keluarga dan hasil perkembangan.']],
  parents_10: ['behavioral_maturity','parent_feedback_use',['Masukan hanya didengar|Saran wali tidak dikelompokkan atau dihubungkan dengan keputusan.','Sebagian masukan ditanggapi|Kasus tertentu mendapat respons, tetapi prioritas tidak jelas.','Masukan dianalisis dan dipilih|Tema, risiko, kemampuan lembaga, dan keputusan tindak lanjut terdokumentasi.','Hasil perbaikan diperiksa|Perubahan layanan dan respons wali setelahnya ditinjau.','Siklus umpan balik terbuka|Pesantren menjelaskan hasil dan terus memperbaiki cara menghimpun masukan.']],

  digital_01: ['evidence_state','data_source_of_truth',['Banyak versi tanpa rujukan|Data yang sama berbeda antarfile, aplikasi, dan pemegang catatan.','Sumber utama diketahui informal|Orang tertentu tahu data mana yang dipakai, tetapi belum ditetapkan.','Sumber utama per data jelas|Pemilik, lokasi, format, dan pihak pembaru sudah ditentukan.','Konsistensi sumber diperiksa|Salinan ganda dan perbedaan dengan sumber utama ditindaklanjuti.','Arsitektur data disederhanakan|Sumber dan aliran data diperbaiki dari pola penggunaan.']],
  digital_02: ['behavioral_maturity','data_update_control',['Perubahan lambat dan berulang|Data diperbarui di banyak tempat tanpa urutan yang jelas.','Pembaruan bergantung orang tertentu|Sebagian perubahan cepat, tetapi duplikasi masih sering terjadi.','Alur pembaruan ditetapkan|Pemicu, pemilik, waktu, dan sistem tujuan untuk perubahan sudah jelas.','Ketepatan pembaruan dipantau|Keterlambatan dan data ganda ditemukan serta diselesaikan.','Proses pembaruan dioptimalkan|Langkah dan integrasi diperbaiki dari jenis kesalahan yang berulang.']],
  digital_03: ['frequency','data_quality_review',['Tidak pernah diperiksa|Kesalahan diketahui ketika data sudah dipakai atau dikeluhkan.','Diperiksa saat dibutuhkan|Tim membersihkan data menjelang laporan tertentu.','Pemeriksaan rutin berjalan|Kelengkapan, ketepatan, kebaruan, dan konsistensi diperiksa terjadwal.','Temuan kualitas ditutup|Kesalahan memiliki pemilik, penyebab, koreksi, dan tenggat.','Kontrol pencegahan diperkuat|Aturan input diperbaiki dari pola kesalahan.']],
  digital_04: ['behavioral_maturity','data_correction_traceability',['Data langsung ditimpa|Nilai lama, alasan, dan orang yang mengubah tidak dapat diketahui.','Koreksi dicatat sebagian|Perubahan penting kadang diberi catatan, tetapi tidak konsisten.','Koreksi memiliki jejak|Kesalahan, nilai lama-baru, alasan, persetujuan, dan waktu dapat ditelusuri.','Jejak koreksi diperiksa|Perubahan tidak wajar dan penyebab kesalahan berulang ditinjau.','Proses koreksi disempurnakan|Hak dan validasi diperbarui dari pola kesalahan.']],
  digital_05: ['behavioral_maturity','data_access_control',['Akses terlalu terbuka|Orang dapat melihat atau mengubah data di luar kebutuhan tugasnya.','Pembatasan bergantung pembagian tautan|Ada kontrol, tetapi akun bersama dan hak lama masih digunakan.','Hak sesuai tugas|Akses lihat, ubah, unduh, dan hapus diberikan berdasarkan peran.','Akses ditinjau|Akun, mutasi personil, dan aktivitas tidak wajar diperiksa.','Kontrol diperbarui berbasis risiko|Hak dan autentikasi diperkuat dari sensitivitas data serta insiden.']],
  digital_06: ['behavioral_maturity','personal_data_protection',['Data dibagikan bebas|Informasi santri dan keluarga dikirim tanpa batas tujuan atau penerima.','Kehati-hatian bersifat pribadi|Sebagian staf menjaga data, tetapi aturan dan kanal belum jelas.','Penggunaan data dibatasi|Data dikumpulkan seperlunya dan dibagikan hanya kepada pihak berwenang.','Kepatuhan dan insiden dipantau|Pembagian salah, kehilangan, dan permintaan akses ditindaklanjuti.','Perlindungan diperkuat|Praktik diperbarui dari risiko, teknologi, dan kebutuhan keluarga.']],
  digital_07: ['frequency','data_backup',['Tidak ada backup|Kehilangan perangkat dapat menghilangkan data penting.','Backup dilakukan sesekali|Salinan dibuat manual tanpa jadwal atau pemilik yang pasti.','Backup rutin dan terpisah|Cakupan, jadwal, lokasi, retensi, dan penanggung jawab sudah jelas.','Keberhasilan backup dipantau|Kegagalan dan data yang terlewat mendapat tindak lanjut.','Strategi backup disesuaikan|Frekuensi dan lokasi diperbarui dari perubahan risiko dan volume.']],
  digital_08: ['evidence_state','backup_restore_test',['Belum pernah diuji|Keberadaan salinan dianggap cukup tanpa mencoba pemulihan.','Pernah diuji sebagian|Beberapa file dipulihkan, tetapi sistem penting belum tercakup.','Uji pemulihan terdokumentasi|Data dipulihkan di lingkungan aman dengan hasil dan waktu tercatat.','Temuan uji ditutup|Kegagalan, kelambatan, dan akses yang kurang ditindaklanjuti.','Kesiapan pemulihan ditingkatkan|Skenario dan target waktu diperbarui dari hasil latihan.']],
  digital_09: ['behavioral_maturity','technology_process_fit',['Alat dipilih karena tren|Aplikasi ditambah tanpa masalah proses dan pengguna yang jelas.','Manfaat diasumsikan|Kebutuhan dibahas, tetapi alur dan adopsi belum diuji.','Alat sesuai proses|Masalah, pengguna, kebutuhan, alternatif, dan hasil yang diharapkan dinilai.','Pemakaian dan manfaat diperiksa|Adopsi, duplikasi kerja, biaya, dan hasil ditinjau setelah penerapan.','Portofolio alat dirapikan|Aplikasi dipertahankan, diintegrasikan, atau dihentikan berdasarkan bukti.']],
  digital_10: ['behavioral_maturity','data_use_in_decision',['Data hanya dikumpulkan|Laporan dibuat tetapi keputusan tetap berdasarkan kebiasaan.','Data dilihat sesekali|Angka dipakai untuk menjelaskan masalah setelah terjadi.','Data utama dibahas rutin|Indikator yang relevan menjadi bahan rapat dan keputusan.','Dampak keputusan dipantau|Perubahan indikator setelah tindakan diperiksa.','Pertanyaan keputusan dipertajam|Data dan analisis diperbarui dari pelajaran pengambilan keputusan.']],

  quality_01: ['behavioral_maturity','values_to_behavior',['Nilai berhenti sebagai slogan|Orang belum tahu tindakan sehari-hari yang menunjukkan nilai pesantren.','Contoh bergantung penafsiran|Sebagian pimpinan memberi contoh, tetapi maknanya berbeda antarunit.','Perilaku utama dijelaskan|Setiap nilai memiliki contoh tindakan yang dapat dilihat dan dipraktikkan.','Konsistensi perilaku ditinjau|Teladan, pelanggaran, dan dilema dibahas dengan acuan yang sama.','Nilai terus dihidupkan|Contoh perilaku diperbarui dari tantangan dan pembelajaran organisasi.']],
  quality_02: ['behavioral_maturity','leadership_role_modeling',['Teladan tidak konsisten|Aturan yang dikoreksi pada staf tidak selalu dilakukan penanggung jawab.','Koreksi bergantung orang|Sebagian pimpinan konsisten, tetapi standar dan caranya berbeda.','Teladan dan koreksi selaras|Pimpinan menjalankan standar serta memberi koreksi yang jelas dan adil.','Konsistensi kepemimpinan diperiksa|Perbedaan antarunit dan dampak koreksi ditinjau.','Praktik kepemimpinan diperbaiki|Umpan balik staf dan hasil kerja dipakai memperkuat keteladanan.']],
  quality_03: ['extent','psychological_safety',['Orang memilih diam|Masalah dan kesalahan disembunyikan karena takut disalahkan atau dirugikan.','Aman hanya kepada orang tertentu|Sebagian staf dapat bicara, tetapi perlindungan bergantung hubungan pribadi.','Jalur bicara aman tersedia|Staf dapat menyampaikan masalah dengan respons yang menghargai fakta dan perlindungan.','Pengalaman pelapor dipantau|Balasan, kerahasiaan, tindakan balasan, dan tindak lanjut diperiksa.','Budaya belajar diperkuat|Pola laporan dipakai mengurangi ketakutan dan memperbaiki respons pimpinan.']],
  quality_04: ['behavioral_maturity','feedback_case_fairness',['Respons tidak dapat ditelusuri|Masukan dapat diabaikan atau diputuskan tanpa alasan yang diketahui.','Kasus besar ditangani|Sebagian laporan tercatat, tetapi kriteria dan waktu respons belum konsisten.','Penanganan adil dan terlacak|Penerimaan, telaah, keputusan, alasan, tindakan, dan penutupan tercatat.','Konsistensi keputusan diperiksa|Kasus sejenis, keterlambatan, dan kepuasan penyelesaian ditinjau.','Sistem penanganan diperbaiki|Kriteria dan alur diperbarui dari pola kasus serta risiko.']],
  quality_05: ['frequency','management_review',['Tidak ada review lintas unit|Pimpinan menerima laporan terpisah tanpa pembahasan mutu bersama.','Review muncul saat masalah besar|Pertemuan lintas unit bersifat reaktif dan data tidak tetap.','Management review rutin|Pimpinan menelaah mutu, risiko, data, dan keputusan lintas unit.','Keputusan review dipantau|PIC, tenggat, dan dampak tindakan dibuka pada review berikutnya.','Review semakin tajam|Agenda dan indikator diperbarui dari kualitas keputusan yang dihasilkan.']],
  quality_06: ['behavioral_maturity','cross_unit_verification',['Informasi langsung dipercaya|Keputusan penting memakai satu laporan tanpa memeriksa sumber atau konteks lain.','Verifikasi tergantung keraguan|Data dicek hanya ketika terlihat janggal atau diperdebatkan.','Verifikasi sesuai dampak|Sumber, definisi, waktu, dan konfirmasi unit terkait diperiksa sebelum keputusan penting.','Kesalahan informasi ditinjau|Perbedaan dan keputusan keliru ditelusuri sampai penyebabnya.','Cara verifikasi diperkuat|Kontrol disesuaikan dari risiko dan pola kesalahan lintas unit.']],
  quality_07: ['behavioral_maturity','root_cause_analysis',['Langsung memilih solusi|Tim memperbaiki gejala pertama tanpa memastikan penyebabnya.','Penyebab dibahas secara dugaan|Beberapa kemungkinan disebut, tetapi bukti dan keterkaitannya belum diuji.','Akar masalah dianalisis|Fakta, urutan kejadian, penyebab, dan faktor sistem dibedakan sebelum tindakan.','Ketepatan analisis diperiksa|Hasil tindakan digunakan menguji apakah penyebab utama benar.','Kemampuan analisis berkembang|Metode dan data diperbaiki dari kasus yang berulang.']],
  quality_08: ['behavioral_maturity','effectiveness_verification',['Selesai berarti ditutup|Tindakan dianggap berhasil segera setelah dibuat atau dikerjakan.','Hasil diperiksa informal|Tim melihat keadaan sesekali tanpa ukuran dan waktu yang disepakati.','Efektivitas diverifikasi|Ukuran hasil, periode, bukti, dan pihak pemeriksa ditetapkan sejak awal.','Hasil menentukan tindak lanjut|Tindakan dinyatakan efektif, disesuaikan, atau dibuka kembali berdasarkan bukti.','Metode verifikasi disempurnakan|Ukuran dan waktu review diperbaiki dari kemampuan mendeteksi masalah berulang.']],
  quality_09: ['behavioral_maturity','organizational_learning',['Pelajaran tinggal pada orang|Pengetahuan dari masalah hilang ketika orang pindah atau lupa.','Dibagikan secara lisan|Tim tertentu mengetahui pelajaran, tetapi standar kerja tidak berubah.','Pelajaran masuk ke sistem|Temuan penting memperbarui panduan, briefing, pelatihan, atau kontrol.','Penerapan pelajaran diperiksa|Unit terkait ditinjau untuk memastikan perubahan benar-benar digunakan.','Pembelajaran menyebar lintas unit|Pola masalah dan praktik baik dibandingkan serta menjadi standar bersama.']],
  quality_10: ['behavioral_maturity','continuous_improvement',['Perubahan bersifat mendadak|Perbaikan besar dimulai tanpa tujuan, ukuran, atau review yang jelas.','Ada percobaan terpisah|Beberapa unit mencoba cara baru, tetapi hasilnya tidak dibandingkan.','Siklus perbaikan kecil berjalan|Masalah, hipotesis, tindakan, ukuran, waktu, dan review ditetapkan.','Hasil percobaan menentukan keputusan|Cara baru diadopsi, diubah, atau dihentikan berdasarkan bukti.','Perbaikan menjadi kebiasaan|Portofolio eksperimen diprioritaskan dan pelajarannya menyebar.']],
};

const SPECIALS = [
  ['TT','Tidak tahu','Saya belum memiliki informasi yang cukup untuk menilai kondisi ini.'],
  ['BM','Belum mengalami','Saya belum pernah terlibat atau mengalami situasi yang ditanyakan.'],
  ['LW','Lewati','Saya memilih melewati pertanyaan ini tanpa memberikan penilaian.'],
  ['UTB','Usulan tidak berlaku','Pertanyaan ini tidak sesuai dengan tugas atau kondisi yang saya alami.']
];

const questionIndex = new Map(DOMAINS.flatMap((domain, domainIndex) => domain.questions.map((question, questionIndex) => [question.id, { question, domain, domainIndex, questionIndex }])));

function normalOptions(questionId, anchors, answerType) {
  return anchors.map((source, index) => {
    const [label, description] = source.split('|');
    return { answer_option_id: `${questionId}_v03_${index + 1}`, label, description, internal_value: index + 1, gate_signal: answerType === 'behavioral_maturity' || answerType === 'evidence_state' || answerType === 'extent' ? index + 1 : null, diagnostic_signal: answerType === 'frequency' ? index + 1 : null, confidence_signal: 'normal', order: index + 1, instrument_version: ACTIVE_INSTRUMENT_VERSION, excluded_from_score: false };
  });
}

function specialOptions(questionId) {
  return SPECIALS.map(([code,label,description], index) => ({ answer_option_id: `${questionId}_v03_${code.toLowerCase()}`, code, label, description, internal_value: null, gate_signal: null, diagnostic_signal: null, confidence_signal: code === 'TT' ? 'low' : 'not_applicable', order: 90 + index, instrument_version: ACTIVE_INSTRUMENT_VERSION, excluded_from_score: true }));
}

export function getQuestionDefinition(questionId, version = ACTIVE_INSTRUMENT_VERSION) {
  if (version !== ACTIVE_INSTRUMENT_VERSION) return null;
  const source = CURATED[questionId];
  const indexed = questionIndex.get(questionId);
  if (!source || !indexed) return null;
  const [answerType, construct, anchors] = source;
  return { question_id: questionId, question_text: indexed.question.text, indicator_id: `D${String(indexed.domainIndex + 1).padStart(2,'0')}.S${String(Math.floor(indexed.questionIndex / 2) + 1).padStart(2,'0')}.I${String(indexed.questionIndex % 2 + 1).padStart(2,'0')}`, domain_id: indexed.domain.id, domain_code: indexed.domain.code, role: 'all', construct, answer_type: answerType, instrument_version: ACTIVE_INSTRUMENT_VERSION, answer_options: [...normalOptions(questionId, anchors, answerType), ...specialOptions(questionId)] };
}

export function getAllQuestionDefinitions() {
  return DOMAINS.flatMap(domain => domain.questions.map(question => getQuestionDefinition(question.id)).filter(Boolean));
}

export function effectiveInstrumentVersion({ invite, response } = {}) {
  if (response?.submittedAt) return response.instrumentVersion || LEGACY_INSTRUMENT_VERSION;
  return invite?.instrumentVersion || ACTIVE_INSTRUMENT_VERSION;
}

export function answerFromOption(questionId, optionId) {
  const definition = getQuestionDefinition(questionId);
  const option = definition?.answer_options.find(item => item.answer_option_id === optionId);
  if (!option) return null;
  return { answerOptionId: option.answer_option_id, answerType: definition.answer_type, construct: definition.construct, gateSignal: option.gate_signal, diagnosticSignal: option.diagnostic_signal, confidenceSignal: option.confidence_signal, excludedFromScore: option.excluded_from_score, score: option.excluded_from_score ? null : (option.gate_signal ?? option.diagnostic_signal), specialCode: option.code || null };
}

export function answerSignal(answer) {
  if (!answer || answer.excludedFromScore || answer.specialCode) return null;
  const value = answer.gateSignal ?? answer.diagnosticSignal ?? answer.score;
  return Number.isFinite(Number(value)) ? Number(value) : null;
}

export function legacyOptionIdForScore(questionId, score) {
  const numeric = Number(score);
  return Number.isInteger(numeric) && numeric >= 1 && numeric <= 5 ? `${questionId}_v03_${numeric}` : null;
}

export function createVersionedProject(project) { return { ...project, instrumentVersion: ACTIVE_INSTRUMENT_VERSION }; }
export function createVersionedInvite(invite) { return { ...invite, instrumentVersion: ACTIVE_INSTRUMENT_VERSION }; }

export function renderAnswerOptions(definition, answer, escape = value => String(value)) {
  const selectedId = answer?.answerOptionId || legacyOptionIdForScore(definition.question_id, answer?.score);
  const normal = definition.answer_options.filter(item => !item.excluded_from_score);
  const special = definition.answer_options.filter(item => item.excluded_from_score);
  const button = option => `<button type="button" class="answer-btn ${selectedId === option.answer_option_id ? 'selected' : ''}" data-answer-option="${escape(option.answer_option_id)}"><span class="answer-copy"><strong>${escape(option.label)}</strong><span>${escape(option.description)}</span></span></button>`;
  return `<div class="answer-list">${normal.map(button).join('')}</div><details class="special-answer"><summary>Saya belum dapat menilai pertanyaan ini</summary><div class="answer-list special-list">${special.map(button).join('')}</div></details>`;
}
